### ISSUE TITLE
The play json unmarshaller throws a server-specific error

### ISSUE THREAD

**Issue by francisdb** [hseeberger/akka-http-json#202]
My client was throwing exceptions that when logged show cause `akka.http.scaladsl.server.RejectionError: null`

As you can see `RejectionError` is in the server package and it has no proper toString()
PlayJsonSupport can be used on both client and server side, and when used on client side it throws this server exception that has a `null` message.

This was introduced by https://github.com/hseeberger/akka-http-json/pull/96

I suggest to revert this as none of the other XxxSupport classes have this kind of error handling and this is only applicable on server side.

```
akka.http.scaladsl.server.RejectionError: null
    at de.heikoseeberger.akkahttpplayjson.PlayJsonSupport.$anonfun$unmarshaller$1(PlayJsonSupport.scala:75)
    at play.api.libs.json.JsError.recoverTotal(JsResult.scala:77)
    at de.heikoseeberger.akkahttpplayjson.PlayJsonSupport.read$1(PlayJsonSupport.scala:73)
    at de.heikoseeberger.akkahttpplayjson.PlayJsonSupport.$anonfun$unmarshaller$2(PlayJsonSupport.scala:78)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
    at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by francisdb** [comment]
To keep the ability to get more info on the json parsing I would create some other exception type with a proper message. That can then be recovered for serverside code.

**Comment by dhoss** [comment]
Hi, I'm running into this as well, any progress on fixing this?  Or an example of how to extract a useful error message?  Thanks!

**Comment by dhoss** [comment]
I've tried this:

`val r = Http().singleRequest(
      HttpRequest(
        uri = url,
        headers = headers), connectionContext = ctx)
        .flatMap {
          res => Unmarshal(res.entity).to[String]
        }
    r.onComplete {
      case Success(res) => println(s"****** R ${res}")
      case Failure(f) => println(s"**** ERROR ${f.getMessage} ${f.getCause}")
    }`

But I don't get anything helpful out of it:
`**** ERROR null null`

**Comment by dhoss** [comment]
Oddly enough, I can get to the JSON by doing this, but it's obviously pretty hideous:
```
val resFuture = Http().singleRequest(HttpRequest(uri = url, headers = headers), connectionContext = ctx)
val res = Await.result(resFuture, 10 seconds)
val json = Await.result(res.entity.toStrict(10 seconds).map(_.data).map(_.utf8String), 10 seconds)
```

**Comment by hseeberger** [comment]
PR welcome!

**Comment by dhoss** [comment]
@hseeberger sure, I'm happy to contribute, but I'll need some help figuring out a solution to this issue.  I believe the issue I'm seeing that's actually causing the error is probably something in my code, as it works fine when I call it directly in my integration test.  However the issue of the empty exception is still a mystery to me.

**Comment by hseeberger** [comment]
I haven't looked into the details (code), but @francisdb's suggestion above to revert the PR introducing server-side specific error handling sounds reasonlable to me.

**Comment by dhoss** [comment]
@hseeberger I've created #270, let me know your thoughts, thanks!
